import { useCallback } from "react";
import { toast } from "sonner";
import { FileText } from "lucide-react";
import type { CostumeRental, Costume, Student } from "@/data/types";
import { formatCurrency } from "@/lib/format";

interface RentalAgreementProps {
  rental: CostumeRental;
  costume: Costume;
  student: Student;
  studioName: string;
}

/**
 * Generates and opens a printable rental agreement PDF (HTML-based).
 */
export default function RentalAgreement({ rental, costume, student, studioName }: RentalAgreementProps) {
  const handleGenerate = useCallback(() => {
    const today = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Costume Rental Agreement — ${studioName}</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; color: #1a1423; margin: 40px; max-width: 7in; }
  h1 { font-size: 18pt; margin-bottom: 4pt; border-bottom: 2px solid #d4c5c0; padding-bottom: 8pt; }
  h2 { font-size: 14pt; margin-top: 24pt; margin-bottom: 8pt; color: #6b5e68; }
  .section { margin-bottom: 16pt; }
  .row { display: flex; margin: 4pt 0; font-size: 11pt; }
  .label { font-weight: 600; width: 150px; color: #6b5e68; }
  .value { flex: 1; }
  .terms { margin-top: 24pt; font-size: 10pt; line-height: 1.6; color: #4a3f4a; }
  .terms h3 { font-size: 12pt; color: #1a1423; }
  .signature { margin-top: 40pt; }
  .sig-line { border-top: 1px solid #1a1423; width: 250px; margin: 32pt 0 4pt; }
  .footer { margin-top: 40pt; text-align: center; font-size: 8pt; color: #b5a39c; border-top: 1px solid #d4c5c0; padding-top: 12pt; }
</style></head><body>
<h1>${studioName}</h1>
<p style="font-style:italic;color:#6b5e68;margin-top:0;">Costume Rental Agreement</p>

<div class="section">
  <h2>Rental Details</h2>
  <div class="row"><span class="label">Costume:</span><span class="value">${costume.name}</span></div>
  <div class="row"><span class="label">Participant:</span><span class="value">${student.name}</span></div>
  <div class="row"><span class="label">Rental Date:</span><span class="value">${today}</span></div>
  <div class="row"><span class="label">Return By:</span><span class="value">${rental.returnDate ? new Date(rental.returnDate).toLocaleDateString() : "TBD"}</span></div>
</div>

<div class="section">
  <h2>Pricing</h2>
  <div class="row"><span class="label">Rental Fee:</span><span class="value">${formatCurrency(rental.rentalFeeCents)}</span></div>
  <div class="row"><span class="label">Security Deposit:</span><span class="value">${formatCurrency(rental.depositCents)}</span></div>
  <div class="row"><span class="label">Damage Fee (max):</span><span class="value">${formatCurrency(rental.damageFeeCents)}</span></div>
</div>

<div class="terms">
  <h3>Terms & Conditions</h3>
  <ol>
    <li>The rented costume remains the property of ${studioName} at all times.</li>
    <li>The participant agrees to return the costume by the specified return date in the same condition as received, excepting normal wear.</li>
    <li>The security deposit will be refunded upon satisfactory return of the costume, less any damage fees assessed.</li>
    <li>Damage beyond normal wear will be assessed up to the maximum damage fee listed above.</li>
    <li>Late returns may result in additional fees at the studio's discretion.</li>
    <li>Lost or unreturned costumes will incur the full replacement cost plus the damage fee.</li>
  </ol>
</div>

<div class="signature">
  <p style="font-size:10pt;color:#6b5e68;">I have read and agree to the terms and conditions above.</p>
  <div class="sig-line"></div>
  <p style="font-size:10pt;">Parent/Guardian Signature</p>
  <div class="sig-line"></div>
  <p style="font-size:10pt;">Date</p>
</div>

<div class="footer">
  Generated by StudioFlow · ${today}<br>
  ${studioName} · Rental Agreement #${rental.id.slice(0, 8)}
</div>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onload = () => win.print();
    }
    setTimeout(() => URL.revokeObjectURL(url), 5000);
    toast.success("Rental agreement generated");
  }, [rental, costume, student, studioName]);

  return (
    <button
      onClick={handleGenerate}
      className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-4 py-2.5 text-sm font-medium transition hover:bg-secondary"
    >
      <FileText className="h-4 w-4" />
      Generate Agreement
    </button>
  );
}
