-- ============================================================================
-- Migration 017: Registration Invites
-- ----------------------------------------------------------------------------
-- Lets studio owners generate shareable registration links with optional
-- pre-filled email. Parents/members click the link, land on /parent/register
-- with the studio pre-selected and email pre-filled.
--
-- New table: invites
--   token       — UUIDv4 unique token (the ?invite= query param)
--   studio_id   — which studio the invite belongs to
--   email       — optional pre-filled email address
--   status      — pending | accepted | expired
--   created_at  — when the invite was generated
--   expires_at  — when it expires (default 30 days)
--   accepted_at — when the parent completed registration
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS invites (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token         text NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  studio_id     text NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
  email         text,
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'accepted', 'expired')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  accepted_at   timestamptz
);

-- Index for fast token lookups from the registration page
CREATE INDEX IF NOT EXISTS idx_invites_token ON invites(token);

-- Index for listing invites per studio
CREATE INDEX IF NOT EXISTS idx_invites_studio_id ON invites(studio_id);

-- RLS: Studio owners can read/insert their own studio's invites
ALTER TABLE invites ENABLE ROW LEVEL SECURITY;

CREATE POLICY invites_studio_owner_policy ON invites
  FOR ALL
  USING (studio_id IN (
    SELECT id FROM studios WHERE owner_id = user_id()
  ))
  WITH CHECK (studio_id IN (
    SELECT id FROM studios WHERE owner_id = user_id()
  ));

-- Public read: anyone with a valid token can read the invite row (to get studio info)
CREATE POLICY invites_public_token_read ON invites
  FOR SELECT
  USING (true);

-- Only the studio owner can update/delete
CREATE POLICY invites_owner_update ON invites
  FOR UPDATE
  USING (studio_id IN (
    SELECT id FROM studios WHERE owner_id = user_id()
  ));

CREATE POLICY invites_owner_delete ON invites
  FOR DELETE
  USING (studio_id IN (
    SELECT id FROM studios WHERE owner_id = user_id()
  ));

COMMENT ON TABLE invites IS
  'Registration invite links generated by studio owners for parents/members.';
COMMENT ON COLUMN invites.token IS
  'UUID token used as the ?invite= query parameter in the registration link.';
COMMENT ON COLUMN invites.email IS
  'Optional pre-filled email address for the registration form.';
COMMENT ON COLUMN invites.status IS
  'pending = not yet used, accepted = registration completed, expired = past expires_at.';

COMMIT;
